FROM composer:1.7.2

COPY ./ch01/composer_laravel.lock /php-app/composer.lock
COPY ./ch01/Gemfile_rails.lock /ruby-app/Gemfile.lock
COPY ./ch01/package-lock_react.json /node-app/package-lock.json
COPY ./ch01/Pipfile.lock /python-app/Pipfile.lock
COPY ./ch01/Cargo.lock /rust-app/Cargo.lock

#EXPOSE 80000
